# Generated by Django 4.0.5 on 2022-06-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EachDetail',
        ),
    ]
