# Generated by Django 4.0.5 on 2022-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_whose_account_to_repay_repay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repay',
            name='date',
            field=models.DateField(),
        ),
    ]
